################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

header:
  productDescription: Fraud Mitigation provides merchants the ability to decision authorization based on a number of in flight component attributes. The underlying infrastructure provides the gateway an environment that ultimately protects the firms asset by recognizing fraud patterns and stopping transactions that may fit this mold. The integration provides quick and easy access to a combination of proprietary and partner capabilities.
getStarted: /docs/getting-started.md
benefits:
  - title: Maximize Revenue
    description: Increase the number of approved transactions, securely expand your business and increase wallet share.
  - title: Prioritize Scalability
    description: Automate decisions and lower operational cost to improve your team’s efficiency. Manage several fraud mitigation tools though a single vendor relationship.
  - title: Improve Customer Experience
    description: Ensure a seamless customer payment and checkout experience with decisions returned in milliseconds.
guides:
  - title: Online Payments
    description: Protect online merchants by reducing fraud and improving approval rates.
    link: docs/onlinepayments.md
  - title: Identify Bad Actors
    description: Empower the platform to root out serial refund and promotional fraudsters.
    link: docs/identification.md
  - title: Orchestration
    description: Leverage a single gateway connection to provide linkage to numerous partner solutions.
    link: docs/orchestration.md
featuredFeatures:
  - title: Control
    groupName: Guides
    featured: true
    description: Identify unusual payment patterns and help stop fraudulent transactions by leveraging a flexible rules-based solution with built-in standard and customizable rulesets.
    relatedDocs:
      - link: docs/control.md
        title: Control
    relatedAPIs:
      - type: post
        path: /{gatewayName}/pre-evaluate/clientID/{clientID}
        title: PreEvaluate
  - title: Score
    groupName: Guides
    featured: true
    description: Drive decision-making, identify fraudulent networks and authenticate valid customers by evaluating transactions in real-time with machine learning-based scoring tailored to your business.
    relatedDocs:
      - link: docs/score.md
        title: Score
    relatedAPIs:
      - type: post
        path: /{gatewayName}/pre-evaluate/clientID/{clientID}
        title: PreEvaluate
  - title: Guarantee
    groupName: Guides
    description: Shift the financial risk and approve more online orders with chargeback guarantee.
    relatedDocs:
      - link: docs/guarantee.md
        title: Guarantee
    relatedAPIs:
      - type: post
        path: /{gatewayName}/pre-evaluate/clientID/{clientID}
        title: PreEvaluate
